-- Histórico de músicas acessadas (US16). Diferente de curtida_musica,
-- aqui um mesmo usuário pode ter várias linhas para a mesma música (uma
-- por visualização), por isso a chave é um id surrogate e não
-- (id_usuario, id_musica).
CREATE TABLE historico_musica (
    id_historico BIGINT GENERATED BY DEFAULT AS IDENTITY,
    id_usuario BIGINT NOT NULL,
    id_musica BIGINT NOT NULL,
    visualizado_em TIMESTAMP WITH TIME ZONE
        NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_historico_musica
        PRIMARY KEY (id_historico),

    CONSTRAINT fk_historico_musica_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario (id)
        ON DELETE CASCADE,

    CONSTRAINT fk_historico_musica_musica
        FOREIGN KEY (id_musica)
        REFERENCES musica (id_musica)
        ON DELETE CASCADE
);

-- Cobre tanto a consulta "última música vista pelo usuário" (checar
-- repetição consecutiva antes de inserir) quanto a listagem ordenada
-- do histórico, sem precisar ordenar em memória.
CREATE INDEX idx_historico_musica_usuario
    ON historico_musica (id_usuario, visualizado_em DESC);
